#!/bin/bash
echo "====================================================================="
echo "🚀 FastAPI Authentication Server - Quick Demo"
echo "====================================================================="
echo ""
echo "📝 Created Files:"
echo "  • api_server.py - FastAPI server with /register and /login endpoints"
echo "  • API_SERVER_README.md - Complete documentation"
echo ""
echo "📦 Dependencies Installed (in venv):"
echo "  • FastAPI - Web framework"
echo "  • Uvicorn - ASGI server"
echo "  • Pydantic - Data validation"
echo "  • httpx - HTTP client for testing"
echo ""
echo "🎯 Features Implemented:"
echo "  ✅ POST /register - Create new user account"
echo "  ✅ POST /login - Authenticate user"
echo "  ✅ Pydantic validation (username 3-50 chars, password 8+ chars)"
echo "  ✅ Integrates with existing AuthManager (core/auth)"
echo "  ✅ Returns proper HTTP status codes (201, 200, 400, 401, 422)"
echo ""
echo "🚀 To Run the Server:"
echo "-------------------------------------------------------------------"
echo "  source venv/bin/activate"
echo "  python3 api_server.py"
echo ""
echo "  Then visit: http://localhost:8000/docs (Interactive API docs)"
echo "-------------------------------------------------------------------"
echo ""
echo "📖 Example API Calls (using curl):"
echo ""
echo "# Register a user"
echo 'curl -X POST http://localhost:8000/register \'
echo '  -H "Content-Type: application/json" \'
echo '  -d '"'"'{"username": "boss", "password": "SecurePass123!"}'"'"
echo ""
echo "# Login"
echo 'curl -X POST http://localhost:8000/login \'
echo '  -H "Content-Type: application/json" \'
echo '  -d '"'"'{"username": "boss", "password": "SecurePass123!"}'"'"
echo ""
echo "====================================================================="
