global:
  resolve_timeout: 5m

route:
  receiver: telegram_primary
  group_by: ['job']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 3h
  routes:
    - matchers:
        - team="trading"
      receiver: telegram_trading
      group_wait: 0s
      group_interval: 5s
      repeat_interval: 30m

receivers:
  - name: telegram_primary
    telegram_configs:
      - bot_token: '__TELEGRAM_BOT_TOKEN__'
        chat_id: __TELEGRAM_CHAT_ID__
        parse_mode: ''
        message: |-
          🔔 *{{ .Status | toUpper }}*: {{ (index .Alerts 0).Labels.alertname }}
          *Job*: {{ (index .Alerts 0).Labels.job }}
          *Instance*: {{ (index .Alerts 0).Labels.instance }}
          *Severity*: {{ (index .Alerts 0).Labels.severity | default "info" }}
          *Summary*: {{ (index .Alerts 0).Annotations.summary | default "" }}
          *Description*: {{ (index .Alerts 0).Annotations.description | default "" }}
          *Started*: {{ (index .Alerts 0).StartsAt }}
          *Link*: {{ .ExternalURL }}
        send_resolved: true

  - name: telegram_trading
    telegram_configs:
      - bot_token: '__TELEGRAM_BOT_TOKEN__'
        chat_id: __TELEGRAM_CHAT_ID__
        parse_mode: HTML
        message: |-
          <b>📈 Trading Alert</b>
          <b>{{ (index .Alerts 0).Labels.alertname }}</b>
          {{- range .Alerts }}
          • {{ .Annotations.summary }} — {{ .Annotations.desc }}
            <i>labels:</i> {{ .Labels }}
          {{- end }}
        send_resolved: true
