groups:
- name: trading.rules
  rules:
  # Price crosses (example for SET50)
  - alert: PriceAboveLevel
    expr: trading_price_last{symbol="SET50"} > 850.0
    for: 0m
    labels:
      severity: info
      team: trading
    annotations:
      summary: "SET50 > 850"
      desc: "Last price {{ $value }} crossed above 850"

  - alert: PriceBelowLevel
    expr: trading_price_last{symbol="SET50"} < 820.0
    for: 0m
    labels:
      severity: info
      team: trading
    annotations:
      summary: "SET50 < 820"
      desc: "Last price {{ $value }} crossed below 820"

  # Risk: drawdown / margin
  - alert: DrawdownExceeded
    expr: trading_account_net_pnl < -15000    # adjust to your risk
    for: 0m
    labels:
      severity: warning
      team: trading
    annotations:
      summary: "Net PnL below threshold"
      desc: "Net PnL: {{ $value }}"

  - alert: MarginUsageHigh
    expr: trading_account_margin_used_pct > 70
    for: 1m
    labels:
      severity: warning
      team: trading
    annotations:
      summary: "Margin usage > 70%"
      desc: "Margin usage: {{ $value }}%"

  # Position size guard
  - alert: PositionTooLarge
    expr: abs(trading_position_contracts) > 6
    for: 0m
    labels:
      severity: warning
      team: trading
    annotations:
      summary: "Position size over limit"
      desc: "Contracts: {{ $value }}"

  # Paula AI signals
  - alert: PaulaBuySignal
    expr: |
      (trading_signal{strategy="paula_v1"} == 1)
      and ignoring(reason,timeframe)
      (trading_signal_confidence{strategy="paula_v1"} > 0.6)
    for: 15s
    labels:
      severity: info
      team: trading
      action: buy
    annotations:
      summary: "🟢 PAULA BUY {{ $labels.symbol }} ({{ $labels.timeframe }})"
      desc: "{{ $labels.reason }} | Confidence > 0.6"

  - alert: PaulaSellSignal
    expr: |
      (trading_signal{strategy="paula_v1"} == -1)
      and ignoring(reason,timeframe)
      (trading_signal_confidence{strategy="paula_v1"} > 0.6)
    for: 15s
    labels:
      severity: warning
      team: trading
      action: sell
    annotations:
      summary: "🔴 PAULA SELL {{ $labels.symbol }} ({{ $labels.timeframe }})"
      desc: "{{ $labels.reason }} | Confidence > 0.6"
