name: 02luka
networks:
  02luka-net: {}

services:
  redis:
    image: redis:7-alpine
    command: ["redis-server","--appendonly","yes"]
    healthcheck:
      test: ["CMD","redis-cli","PING"]
      interval: 10s
      timeout: 3s
      retries: 30
    volumes:
      - luka-ops_redis_data:/data
    networks:
      02luka-net:
        aliases: [ "02luka-redis", "redis" ]
    restart: unless-stopped

  http_redis_bridge:
    image: node:20-alpine
    working_dir: /app/g
    command: ["node","tools/services/http_redis_bridge.cjs"]
    volumes:
      - ..:/app/g
    environment:
      - REDIS_URL=${REDIS_URL:-redis://02luka-redis:6379}
      - BRIDGE_PORT=${BRIDGE_PORT:-8788}
    ports:
      - "8788:8788"
    depends_on:
      redis:
        condition: service_healthy
    networks: [ "02luka-net" ]
    restart: unless-stopped

  clc_listener:
    image: node:20-alpine
    working_dir: /app/g
    command: ["node","tools/services/redis_export_mode_listener.cjs"]
    volumes:
      - ..:/app/g
    environment:
      - REDIS_URL=${REDIS_URL:-redis://02luka-redis:6379}
      - CLC_EXPORT_MODE_CHANNEL=${CLC_EXPORT_MODE_CHANNEL:-gg:clc:export_mode}
    depends_on:
      redis:
        condition: service_healthy
    networks: [ "02luka-net" ]
    restart: unless-stopped

  ops_health_watcher:
    image: node:20-alpine
    working_dir: /app/g
    command: ["node","tools/services/ops_health_watcher.cjs"]
    volumes:
      - ..:/app/g
    environment:
      - OPS_HEALTH_URL=${OPS_HEALTH_URL:-https://ops.theedges.work}
    depends_on:
      - redis
    networks: [ "02luka-net" ]
    restart: unless-stopped

  health_server:
    image: node:20-alpine
    working_dir: /app/g
    command: ["node","tools/health/health_server.cjs"]
    volumes:
      - ..:/app/g:ro
    environment:
      - HEALTH_PORT=${HEALTH_PORT:-4000}
    ports:
      - "4000:4000"
    networks: [ "02luka-net" ]
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "sh", "-lc", "apk add --no-cache curl >/dev/null 2>&1 || true; curl -fsS http://localhost:4000/ping >/dev/null"]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped
    labels:
      com.02luka.role: "health-server"
      com.02luka.stack: "core"

volumes:
  luka-ops_redis_data:
