#!/usr/bin/env zsh
# End-to-end regression for the WO pipeline

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

source "$SCRIPT_DIR/lib_wo_common.zsh"

INBOX_DIR="$REPO_ROOT/bridge/inbox/CLC"
STATE_DIR="$REPO_ROOT/followup/state"
GENERATOR="$HOME/02luka/tools/claude_tools/generate_followup_data.zsh"

cleanup() {
  if [[ "${KEEP_TEST_STATE:-0}" == "1" ]]; then
    return
  fi
  [[ -n "${TMP_WO_PATH:-}" && -f "$TMP_WO_PATH" ]] && rm -f "$TMP_WO_PATH"
  [[ -n "${STATE_FILE_PATH:-}" && -f "$STATE_FILE_PATH" ]] && rm -f "$STATE_FILE_PATH"
}

trap cleanup EXIT

main() {
  ensure_dir "$INBOX_DIR"
  ensure_dir "$STATE_DIR"

  local test_id="WO-TEST-PIPELINE-E2E"
  TMP_WO_PATH="$INBOX_DIR/$test_id.yaml"
  STATE_FILE_PATH="$STATE_DIR/$test_id.json"

  rm -f "$TMP_WO_PATH" "$STATE_FILE_PATH"

  cat > "$TMP_WO_PATH" <<EOF_WO
id: $test_id
title: "E2E test WO"
summary: "Validate WO pipeline"
owner: "cls"
priority: "high"
category: "pipeline"
due_date: "2025-12-01"
goal: "Ensure processors + executor succeed"
progress: 10
notes: "autogenerated by test"
EOF_WO

  "$SCRIPT_DIR/apply_patch_processor.zsh"
  "$SCRIPT_DIR/json_wo_processor.zsh"
  "$SCRIPT_DIR/wo_executor.zsh"
  "$SCRIPT_DIR/followup_tracker.zsh"

  if [[ ! -f "$STATE_FILE_PATH" ]]; then
    echo "State file missing: $STATE_FILE_PATH" >&2
    exit 1
  fi

  "$WO_PIPELINE_PYTHON_BIN" - "$STATE_FILE_PATH" <<'PY'
import json, sys, pathlib
path = pathlib.Path(sys.argv[1])
data = json.loads(path.read_text(encoding='utf-8'))
errors = []
if data.get('status') != 'done':
    errors.append(f"status expected 'done' got {data.get('status')}")
if int(data.get('progress', 0)) < 100:
    errors.append('progress expected 100')
if data.get('owner') != 'cls':
    errors.append('owner mismatch')
if errors:
    raise SystemExit('\n'.join(errors))
PY

  if [[ -x "$GENERATOR" ]]; then
    "$GENERATOR" >/dev/null || {
      echo "WARN: generate_followup_data.zsh failed" >&2
      exit 1
    }
  fi

  echo "E2E pipeline test PASSED"
}

main "$@"
