#!/usr/bin/env zsh
set -e

echo "== Phase 5: Post-Codex Verification Sync Prep (251114) =="

REPO_ROOT="$HOME/02luka/g"
BRANCH_NAME="ai/post-codex-verification-251114"
REPORT_DIR="$REPO_ROOT/reports"
REPORT_FILE="$REPORT_DIR/sync_activation_251114.md"

cd "$REPO_ROOT" || {
  echo "❌ Repo not found at $REPO_ROOT"
  exit 1
}

echo "→ Checking git repository..."
git rev-parse --is-inside-work-tree >/dev/null 2>&1 || {
  echo "❌ Not a git repository: $REPO_ROOT"
  exit 1
}

CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
STATUS_CLEAN="$(git status --porcelain)"

if [[ -n "$STATUS_CLEAN" ]]; then
  echo "❌ Working tree is not clean. Please review and clean up before Phase 5."
  git status
  exit 1
fi

echo "✅ Git repo OK. Current branch: $CURRENT_BRANCH"
echo

echo "→ Ensuring report directory exists..."
mkdir -p "$REPORT_DIR"

echo "→ Creating or switching to branch: $BRANCH_NAME"

if git show-ref --verify --quiet "refs/heads/$BRANCH_NAME"; then
  echo "   Branch already exists. Checking it out..."
  git checkout "$BRANCH_NAME"
else
  echo "   Creating new branch from current HEAD..."
  git checkout -b "$BRANCH_NAME"
fi

echo
echo "→ Staging all current approved changes..."
git add -A

echo "→ Git status (short):"
git status -sb
echo

COMMIT_MSG="feat(sync): post-codex-verification staging (251114)"
echo "→ Creating commit:"
echo "   $COMMIT_MSG"

if git diff --cached --quiet; then
  echo "⚠️ No staged changes. Nothing to commit. Skipping commit step."
else
  git commit -m "$COMMIT_MSG"
fi

echo
echo "→ Pushing branch to origin: $BRANCH_NAME"
git push -u origin "$BRANCH_NAME"

echo
echo "→ Writing Phase 5 sync activation report to:"
echo "   $REPORT_FILE"

cat > "$REPORT_FILE" <<'EOF'
# Phase 5 Sync Activation Report
**Date:** 2025-11-14  
**Branch:** ai/post-codex-verification-251114  
**Status:** BRANCH CREATED & PUSHED

## Summary

- Codex review verdict: **Option A - Approve All**
- Post-verification sync branch created and pushed:
  - Branch: `ai/post-codex-verification-251114`
  - Purpose: Stage all approved changes after Codex verification

## Steps Executed

1. Verified:
   - Git repo at `~/02luka/g`
   - Working tree clean (no uncommitted changes)
2. Created/switch branch:
   - `ai/post-codex-verification-251114`
3. Staged all files:
   - `git add -A`
4. Commit (if needed):
   - `feat(sync): post-codex-verification staging (251114)`
5. Pushed:
   - `git push -u origin ai/post-codex-verification-251114`

## Next Steps (Manual / Future Automation)

1. Review branch on GitHub:
   - Compare `ai/post-codex-verification-251114` vs `main`
2. If everything is correct:
   - Merge into `main` via PR (recommended)
3. After merge:
   - Re-enable any disabled auto-sync / auto-commit logic
   - Monitor first sync for issues

## Notes

- This report was generated by `tools/phase5_enable_sync_251114.zsh`.
- Codex changes were already verified as **SAFE** in:
  - `g/reports/codex_verification_diff_20251114.md`
  - `g/reports/codex_automated_analysis_20251114.md`
  - `g/reports/codex_review_verdict_20251114.md`

**Status:** ✅ Phase 5 branch prepared and pushed. Awaiting merge + sync enablement.
EOF

echo
echo "✅ Phase 5 complete: branch '$BRANCH_NAME' pushed and report written."
echo "   - Report: $REPORT_FILE"
echo "   - Next: open PR from '$BRANCH_NAME' → 'main' and review via GitHub."
