#!/usr/bin/env bash
# Phase 20 — Coordinator Load Test
# Stress test for CI Coordinator
# WO-ID: WO-251107-PHASE-20-COORDINATOR-LOAD

set -euo pipefail

BASE="${BASE:-$HOME/02luka}"
REDIS_URL="${LUKA_REDIS_URL:-redis://127.0.0.1:6379}"
CHANNEL="ci:events"
REPO="${REPO:-Ic1558/02luka}"

# Test parameters
CONCURRENT="${CONCURRENT:-10}"
TOTAL="${TOTAL:-100}"
DELAY_MS="${DELAY_MS:-100}"

REPORT_DIR="${BASE}/g/reports/ci"
REPORT_FILE="${REPORT_DIR}/coordinator_load_test_$(date -u +%Y%m%dT%H%M%SZ).md"

mkdir -p "$REPORT_DIR"

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
# shellcheck disable=SC2034
YELLOW='\033[1;33m'
NC='\033[0m'

echo "=========================================="
echo "Coordinator Load Test"
echo "=========================================="
echo "Concurrent: $CONCURRENT"
echo "Total: $TOTAL"
echo "Delay: ${DELAY_MS}ms"
echo "Channel: $CHANNEL"
echo ""

# Check Redis connection
if ! redis-cli -u "$REDIS_URL" PING >/dev/null 2>&1; then
  echo -e "${RED}✗ Redis not available${NC}"
  exit 1
fi

echo -e "${GREEN}✓ Redis connected${NC}"
echo ""

# Generate test events
generate_event() {
  local pr=$1
  local type=$2
  cat <<JSON
{
  "type": "$type",
  "repo": "$REPO",
  "pr": $pr,
  "time": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}
JSON
}

# Publish event
publish_event() {
  local event=$1
  redis-cli -u "$REDIS_URL" PUBLISH "$CHANNEL" "$event" >/dev/null 2>&1
}

# Run load test
echo "Starting load test..."
echo ""

start_time=$(date +%s)
success=0
failed=0

# Generate test PR numbers (use random numbers in valid range)
for i in $(seq 1 "$TOTAL"); do
  pr=$((200 + (RANDOM % 50)))  # PR numbers 200-250
  event=$(generate_event "$pr" "pr.rerun.request")
  
  if publish_event "$event"; then
    ((success++))
  else
    ((failed++))
  fi
  
  # Small delay between events
  sleep "0.${DELAY_MS}"
  
  # Progress indicator
  if ((i % 10 == 0)); then
    echo -n "."
  fi
done

end_time=$(date +%s)
duration=$((end_time - start_time))

echo ""
echo ""

# Generate report
{
  echo "# Coordinator Load Test Report"
  echo ""
  echo "**Timestamp:** $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo "**Duration:** ${duration}s"
  echo ""
  echo "## Test Parameters"
  echo ""
  echo "- **Concurrent:** $CONCURRENT"
  echo "- **Total Events:** $TOTAL"
  echo "- **Delay:** ${DELAY_MS}ms"
  echo "- **Channel:** $CHANNEL"
  echo "- **Redis URL:** $REDIS_URL"
  echo ""
  echo "## Results"
  echo ""
  echo "- **Success:** $success"
  echo "- **Failed:** $failed"
  echo "- **Duration:** ${duration}s"
  echo "- **Throughput:** $((TOTAL / duration)) events/s"
  echo ""
  echo "## Status"
  echo ""
  if [ $failed -eq 0 ]; then
    echo "✅ **All events published successfully**"
  else
    echo "⚠️  **$failed events failed to publish**"
  fi
  echo ""
  echo "---"
  echo ""
  echo "*Report generated by tools/coordinator_load_test.sh*"
} > "$REPORT_FILE"

echo "=========================================="
echo "Test Complete"
echo "=========================================="
echo -e "Success: ${GREEN}$success${NC}"
echo -e "Failed: ${RED}$failed${NC}"
echo "Duration: ${duration}s"
echo "Throughput: $((TOTAL / duration)) events/s"
echo ""
echo "Report: $REPORT_FILE"

if [ $failed -eq 0 ]; then
  exit 0
else
  exit 1
fi

