#!/usr/bin/env zsh
set -euo pipefail

# Gemini Context Sync
# Updates context/gemini/system_snapshot.md from system_truth_sync_p0.py
# Usage: zsh tools/gemini_context_sync.zsh

ROOT="${LUKA_SOT:-${HOME}/02luka}"
SNAPSHOT_FILE="${ROOT}/context/gemini/system_snapshot.md"
SYNC_SCRIPT="${ROOT}/g/tools/system_truth_sync_p0.py"
LAUNCHAGENT_SCRIPT="${ROOT}/g/tools/launchagent_status.py"

if [[ ! -f "$SYNC_SCRIPT" ]]; then
  echo "Error: system_truth_sync_p0.py not found: $SYNC_SCRIPT" >&2
  exit 1
fi

# Ensure directory exists
mkdir -p "$(dirname "$SNAPSHOT_FILE")"

# Generate snapshot content
{
  echo "# System Snapshot (Auto-Generated Runtime Truth)"
  echo ""
  echo "**Source**: Generated by \`g/tools/system_truth_sync_p0.py\` + \`g/tools/launchagent_status.py\`"
  echo "**Last Updated**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
  echo "**Auto-Update**: Periodic (via LaunchAgent or manual refresh)"
  echo ""
  echo "---"
  echo ""
  echo "## System Health Status"
  echo ""
  echo "### LaunchAgents (P0 Critical)"
  if [[ -f "$LAUNCHAGENT_SCRIPT" ]]; then
    echo "Run: \`python3 g/tools/launchagent_status.py --md\` for current status."
    echo ""
    echo "**P0 Agents** (must be running for GREEN status):"
    echo "- \`com.02luka.mary-gateway-v3\` - Gateway v3 router (if deployed)"
    echo "- \`com.02luka.clc-executor\` - Executes CLC work orders"
    echo "- \`com.02luka.rag.api\` - RAG API server (port 8765)"
    echo "- \`com.02luka.memory.hub\` - Memory hub (if using shared memory system)"
    echo ""
    echo "**Status Logic**:"
    echo "- P0 missing → RED"
    echo "- P0 all running, optional missing → YELLOW"
    echo "- All running → GREEN"
    echo ""
  else
    echo "LaunchAgent status script not found."
    echo ""
  fi
  
  echo "### Sandbox OS L0/L1"
  echo "**Status**: Check via \`g/tools/system_truth_sync_p0.py --md\`"
  echo ""
  echo "Latest report location: \`g/sandbox/os_l0_l1/logs/liam_reports/health_*.json\`"
  echo ""
  
  echo "### Gateway v3 Router"
  echo "**Telemetry File**: \`g/telemetry/gateway_v3_router.jsonl\`"
  echo ""
  echo "Check latest events:"
  echo "\`\`\`bash"
  echo "tail -n 20 g/telemetry/gateway_v3_router.jsonl | jq ."
  echo "\`\`\`"
  echo ""
  
  echo "### System Truth Snapshot"
  echo ""
  # Get system truth sync output (markdown block only)
  cd "$ROOT"
  python3 "$SYNC_SCRIPT" --md 2>/dev/null || echo "Error generating system truth snapshot"
  echo ""
  
  echo "---"
  echo ""
  echo "## How to Refresh This Snapshot"
  echo ""
  echo "### Manual Refresh"
  echo "\`\`\`bash"
  echo "cd ~/02luka"
  echo "zsh tools/gemini_context_sync.zsh"
  echo "\`\`\`"
  echo ""
  echo "### Automatic Refresh"
  echo "- LaunchAgent runs this script periodically (1-2 times per day)"
  echo "- Or trigger via \`/memory refresh\` in Gemini CLI"
  echo ""
  echo "---"
  echo ""
  echo "**Note**: This file is auto-generated. Do not edit manually."
  echo "**For detailed status, run the tools directly.**"
} > "$SNAPSHOT_FILE"

echo "✓ Updated: $SNAPSHOT_FILE"
