#!/usr/bin/env zsh
set -euo pipefail

# pr_reality_hooks_index.zsh
#
# Purpose:
#   Scan known system reports and generate a consolidated
#   "reality hooks" index in g/reports/system/.
#
# Notes:
#   - READ-ONLY over existing reports.
#   - Does not touch workflows, security, or dashboard code.
#   - Safe to run multiple times; creates a new dated file.

SCRIPT_DIR="${0:A:h}"
G_DIR="${SCRIPT_DIR:A:h}"
REPO_ROOT="${G_DIR:A:h}"
REPORTS_DIR="$G_DIR/reports/system"

mkdir -p "$REPORTS_DIR"

iso_stamp() {
  date -u '+%Y%m%dT%H%M%SZ'
}

human_ts() {
  date '+%Y-%m-%d %H:%M:%S %z'
}

OUT_BASENAME="pr_reality_hooks_index_$(iso_stamp).md"
OUT_PATH="$REPORTS_DIR/$OUT_BASENAME"

echo "[*] Generating reality hooks index at: $OUT_PATH"

# Define known PRs and their key report files.
# Adjust / extend as needed.
typeset -A PR_TITLE PR_REPORTS

PR_TITLE[280]="PR #280 — WO Dashboard Hardening"
PR_REPORTS[280]="
pr280_verification_complete_20251115.md
deployment_20251115_052838.md
"

PR_TITLE[283]="PR #283 — Phase2 Sandbox Hardening"
PR_REPORTS[283]="
ci_fix_path_guard_20251115.md
final_ci_fix_status_20251115.md
"

PR_TITLE[287]="PR #287 — Multi-Agent Governance Contract"
PR_REPORTS[287]="
governance_lock_in_20251115.md
"

PR_TITLE[288]="PR #288 — Telemetry Schema Fix"
PR_REPORTS[288]="
telemetry_schema_ci_fix_20251115.md
"

PR_TITLE[289]="PR #289 — CI Infrastructure Improvements"
PR_REPORTS[289]="
codex_sandbox_workflow_fix_20251115.md
memory_guard_zsh_fix_20251115.md
"

PR_TITLE[290]="PR #290 — Orchestrator Restore"
PR_REPORTS[290]="
orchestrator_restore_20251115.md
"

# Future / feature PRs (examples)
PR_TITLE[9991]="Feature — Orchestrator Summary v2"
PR_REPORTS[9991]="
orchestrator_summary_v2_feature_20251116.md
"

PR_TITLE[9992]="Feature — WO History / Timeline View"
PR_REPORTS[9992]="
wo_history_timeline_feature_20251116.md
"

PR_TITLE[9993]="Feature — save.sh Full-Cycle Test Harness"
PR_REPORTS[9993]="
save_sh_full_cycle_test_20251116.md
"

{
  echo "# PR Reality Hooks Index — $(human_ts)"
  echo
  echo "This file lists **reality hooks** (actual reports / logs / test"
  echo "artifacts) for recent PRs and features. Use it in PR descriptions"
  echo "to give reviewers a single place to find evidence."
  echo
  echo "> Generated by: tools/pr_reality_hooks_index.zsh"
  echo

  for pr in ${(ok)PR_TITLE}; do
    echo "## ${PR_TITLE[$pr]}"
    echo
    echo "| Type | File | Exists | Path |"
    echo "|------|------|--------|------|"

    for fname in ${(f)PR_REPORTS[$pr]}; do
      fname="${fname// /}"
      [[ -z "$fname" ]] && continue
      local_path="$REPORTS_DIR/$fname"
      if [[ -f "$local_path" ]]; then
        echo "| report | \`$fname\` | ✅ | \`g/reports/system/$fname\` |"
      else
        echo "| report | \`$fname\` | ⚠️ missing | \`g/reports/system/$fname\` |"
      fi
    done

    echo
  done

} > "$OUT_PATH"

echo "[+] Reality hooks index written to: $OUT_PATH"
