#!/usr/bin/env zsh
# @created_by: CLC (Claude Code) - Updated by CLS 2025-11-13
# @phase: 20+ (Enhanced for dynamic MLS integration)
# @purpose: Dynamic session save from MLS ledger

set -euo pipefail

# Load env
if [ -f ~/02luka/.env.local ]; then
  source ~/02luka/.env.local
fi

MEM_REPO="${LUKA_MEM_REPO_ROOT:-$HOME/LocalProjects/02luka-memory}"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
SESSION_FILE="$MEM_REPO/g/reports/sessions/session_$TIMESTAMP.md"
TODAY=$(date +"%Y-%m-%d")
MLS_LEDGER="$HOME/02luka/mls/ledger/$(date +%Y-%m-%d).jsonl"

# Ensure directories exist
mkdir -p "$MEM_REPO/g/reports/sessions"

# Check if MLS ledger exists
if [[ ! -f "$MLS_LEDGER" ]]; then
  echo "⚠️  No MLS ledger found for today: $MLS_LEDGER"
  echo "Creating minimal session record..."
fi

# Extract session data from MLS
extract_mls_data() {
  if [[ ! -f "$MLS_LEDGER" ]]; then
    echo '{"total":0,"types":{},"entries":[]}'
    return
  fi
  
  cat "$MLS_LEDGER" | jq -s '{
    total: length,
    types: (group_by(.type) | map({(.[0].type): length}) | add // {}),
    entries: map({
      ts: .ts,
      type: .type,
      title: .title,
      problem: .problem // "",
      solution: .solution // "",
      tags: .tags // []
    })
  }'
}

# Get agent name (CLS/CLC/GG)
AGENT="${SESSION_AGENT:-CLS}"

# Generate session content
echo "📝 Generating session from MLS ledger..."
MLS_DATA=$(extract_mls_data)
TOTAL_ENTRIES=$(echo "$MLS_DATA" | jq -r '.total')

# Count by type
SOLUTIONS=$(echo "$MLS_DATA" | jq -r '.types.solution // 0')
IMPROVEMENTS=$(echo "$MLS_DATA" | jq -r '.types.improvement // 0')
FAILURES=$(echo "$MLS_DATA" | jq -r '.types.failure // 0')
PATTERNS=$(echo "$MLS_DATA" | jq -r '.types.pattern // 0')

# Start writing session file
cat > "$SESSION_FILE" <<EOHEADER
---
title: "$AGENT Session Summary — $(date +"%Y-%m-%d")"
date: $TODAY
type: session
category: system
source: $AGENT
auto_generated: true
tags: [$AGENT, session, auto-generated, mls-derived]
---

# $AGENT Session Summary — $TODAY

**Date:** $TODAY  
**Timestamp:** $(date +"%Y-%m-%d %H:%M:%S %Z")  
**Agent:** $AGENT (Cursor AI Agent)  
**MLS Entries:** $TOTAL_ENTRIES  

---

## Session Statistics

**MLS Entries by Type:**
- Solutions: $SOLUTIONS
- Improvements: $IMPROVEMENTS
- Failures: $FAILURES
- Patterns: $PATTERNS

**Total Activities:** $TOTAL_ENTRIES

---

## Major Activities

EOHEADER

# Add entries grouped by type
for TYPE in solution improvement failure pattern; do
  COUNT=$(echo "$MLS_DATA" | jq -r ".types.$TYPE // 0")
  if [[ $COUNT -gt 0 ]]; then
    # Capitalize first letter (zsh compatible)
    TYPE_CAP="${(C)TYPE}"
    echo "" >> "$SESSION_FILE"
    echo "### ${TYPE_CAP}s ($COUNT)" >> "$SESSION_FILE"
    echo "" >> "$SESSION_FILE"
    
    echo "$MLS_DATA" | jq -r --arg type "$TYPE" '
      .entries[] | select(.type == $type) | 
      "**\(.title)**\n- Time: \(.ts)\n- Problem: \(.problem // "N/A")\n- Solution: \(.solution // "N/A")\n"
    ' >> "$SESSION_FILE"
  fi
done

# Add footer
cat >> "$SESSION_FILE" <<EOFOOTER

---

## Files Modified

_(Auto-detected from MLS entries)_

EOFOOTER

# Extract unique tags
echo "$MLS_DATA" | jq -r '.entries[].tags[]?' | sort -u | while read -r tag; do
  echo "- Tag: $tag" >> "$SESSION_FILE"
done 2>/dev/null || echo "- (No tags recorded)" >> "$SESSION_FILE"

cat >> "$SESSION_FILE" <<EOFOOTER2

---

## Next Steps

EOFOOTER2

# Look for any "followup" or "todo" tags
FOLLOWUPS=$(echo "$MLS_DATA" | jq -r '.entries[] | select(.tags[]? == "followup" or .tags[]? == "todo") | "- [ ] \(.title)"' 2>/dev/null)
if [[ -n "$FOLLOWUPS" ]]; then
  echo "$FOLLOWUPS" >> "$SESSION_FILE"
else
  echo "- Review MLS entries for patterns" >> "$SESSION_FILE"
  echo "- Continue with current phase objectives" >> "$SESSION_FILE"
fi

cat >> "$SESSION_FILE" <<EOFOOTER3

---

**Generated by:** $AGENT (Auto-generated from MLS Ledger)  
**Source:** $MLS_LEDGER  
**Session End:** $(date +"%Y-%m-%d %H:%M:%S %Z")

EOFOOTER3

echo "✅ Session saved: $SESSION_FILE"
echo "   Total entries: $TOTAL_ENTRIES"
echo "   File size: $(du -h "$SESSION_FILE" | cut -f1)"

# Auto-commit to memory repo
if [[ -d "$MEM_REPO/.git" ]]; then
  echo ""
  echo "📦 Committing to memory repo..."
  cd "$MEM_REPO"
  git add "g/reports/sessions/session_$TIMESTAMP.md"
  git commit -m "session: $AGENT session summary $TODAY

Auto-generated from MLS ledger:
- Solutions: $SOLUTIONS
- Improvements: $IMPROVEMENTS
- Failures: $FAILURES
- Total entries: $TOTAL_ENTRIES

Timestamp: $TIMESTAMP" || echo "⚠️  Commit failed (may already be committed)"
  
  echo "✅ Committed to memory repo"
else
  echo "⚠️  Memory repo not a git repository, skipping commit"
fi

# Trigger hub index refresh if available
if [[ -f ~/02luka/tools/hub_index_now.zsh ]]; then
  echo ""
  echo "🔄 Triggering hub index refresh..."
  ~/02luka/tools/hub_index_now.zsh 2>/dev/null || echo "⚠️  Hub index refresh failed"
fi

echo ""
echo "📊 Session Summary"
echo "─────────────────"
echo "Agent: $AGENT"
echo "Date: $TODAY"
echo "File: $SESSION_FILE"
echo "Entries: $TOTAL_ENTRIES (S:$SOLUTIONS I:$IMPROVEMENTS F:$FAILURES P:$PATTERNS)"
echo ""
echo "✅ Save complete!"
