#!/usr/bin/env zsh
# shellcheck shell=bash
set -euo pipefail

# CI Watcher — Auto rerun failing PRs and log results
# Usage: ./tools/ci_watcher.sh [PR_NUMBER...]
# If no PR numbers provided, auto-detect failing PRs

REPORT_DIR="${HOME}/02luka/g/reports/ci"
mkdir -p "$REPORT_DIR"

# Configurable settings (can be overridden via environment)
BACKOFF_MINUTES="${CI_WATCHER_BACKOFF_MINUTES:-15}"  # Default: 15 minutes
ENABLE_NOTIFICATIONS="${CI_WATCHER_NOTIFICATIONS:-1}"  # Default: enabled (1) or disabled (0)

log_report() {
  local pr_num="$1"
  local status="$2"
  local details="${3:-}"
  local timestamp
  timestamp=$(date -u +%Y%m%d_%H%M%SZ)
  local report_file="${REPORT_DIR}/watcher_${pr_num}_${timestamp}.md"
  
  cat > "$report_file" <<EOF
# CI Watcher Report — PR #$pr_num

**Timestamp:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")
**Status:** $status
**PR URL:** https://github.com/Ic1558/02luka/pull/$pr_num

## Details
$details

## Actions Taken
- Rerun checks triggered via Puppeteer
- Results logged to this file

---
_Generated by ci_watcher.sh_
EOF
  
  echo "📄 Report saved: $report_file"
}

# Get failing PRs if none provided
if [[ $# -eq 0 ]]; then
  echo "🔍 Auto-detecting failing PRs..."
  FAILING_PRS=$(gh pr list --state open --json number,title,statusCheckRollup --limit 20 2>/dev/null | \
    jq -r '.[] | select(.statusCheckRollup != null) | 
      select(.statusCheckRollup | map(select(.conclusion == "FAILURE")) | length > 0) | 
      .number' 2>/dev/null | head -5)
  
  if [[ -z "$FAILING_PRS" ]]; then
    echo "✅ No failing PRs found"
    exit 0
  fi
  
  echo "📋 Found failing PRs: $FAILING_PRS"
  # shellcheck disable=SC2207
  read -ra PR_NUMBERS <<< "$(echo "$FAILING_PRS" | tr '\n' ' ')"
else
  # Validate PR numbers are numeric
  for arg in "$@"; do
    if [[ ! "$arg" =~ ^[0-9]+$ ]]; then
      echo "❌ Invalid PR number: $arg (must be numeric)"
      exit 1
    fi
  done
  PR_NUMBERS=("$@")
fi

# Process each PR
for pr_num in "${PR_NUMBERS[@]}"; do
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "🔄 Processing PR #$pr_num"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  
  # Get PR details
  PR_INFO=$(gh pr view "$pr_num" --json title,url,statusCheckRollup 2>/dev/null || echo "")
  
  if [[ -z "$PR_INFO" ]]; then
    echo "❌ PR #$pr_num not found or inaccessible"
    log_report "$pr_num" "ERROR" "PR not found or inaccessible"
    continue
  fi
  
  PR_TITLE=$(echo "$PR_INFO" | jq -r '.title')
  PR_URL=$(echo "$PR_INFO" | jq -r '.url')
  
  echo "📝 Title: $PR_TITLE"
  echo "🔗 URL: $PR_URL"
  
  # Check current status
  FAILING_CHECKS=$(echo "$PR_INFO" | jq -r '.statusCheckRollup[]? | select(.conclusion == "FAILURE") | .name' | head -5)
  
  if [[ -z "$FAILING_CHECKS" ]]; then
    echo "✅ No failing checks found (may have passed since last check)"
    log_report "$pr_num" "SKIP" "No failing checks found"
    continue
  fi
  
  echo "❌ Failing checks:"
  echo "$FAILING_CHECKS" | while IFS= read -r check; do
    echo "  - $check"
  done
  
  # Check backoff: skip if rerun within configured minutes
  # shellcheck disable=SC2012
  # Use find for portability, fallback to ls if find fails
  LATEST_REPORT=$(find "${REPORT_DIR}" -maxdepth 1 -name "watcher_${pr_num}_*.md" -type f -print0 2>/dev/null | xargs -0 stat -f "%m %N" 2>/dev/null | sort -rn | head -1 | cut -d' ' -f2- || find "${REPORT_DIR}" -maxdepth 1 -name "watcher_${pr_num}_*.md" -type f -exec stat -c "%Y %n" {} \; 2>/dev/null | sort -rn | head -1 | cut -d' ' -f2- || ls -t "${REPORT_DIR}/watcher_${pr_num}_"*.md 2>/dev/null | head -1)
  
  if [[ -n "$LATEST_REPORT" ]]; then
    REPORT_TIME=$(stat -f "%m" "$LATEST_REPORT" 2>/dev/null || stat -c "%Y" "$LATEST_REPORT" 2>/dev/null || echo "0")
    CURRENT_TIME=$(date +%s)
    ELAPSED_MINUTES=$(( (CURRENT_TIME - REPORT_TIME) / 60 ))
    
    if [[ $ELAPSED_MINUTES -lt $BACKOFF_MINUTES ]]; then
      REMAINING=$((BACKOFF_MINUTES - ELAPSED_MINUTES))
      echo "⏸️  Skipping PR #$pr_num (rerun $ELAPSED_MINUTES min ago, wait $REMAINING more min)"
      log_report "$pr_num" "SKIP_BACKOFF" "Rerun triggered $ELAPSED_MINUTES minutes ago (backoff: ${BACKOFF_MINUTES}min)"
      continue
    fi
  fi
  
  # Trigger rerun via Puppeteer
  echo ""
  echo "♻️  Triggering rerun via Puppeteer..."
  
  RERUN_OUTPUT=$(node "${HOME}/02luka/tools/puppeteer/run.mjs" pr-rerun \
    --url "$PR_URL" 2>&1) || {
    echo "⚠️  Puppeteer rerun failed (may need manual rerun)"
    log_report "$pr_num" "RERUN_FAILED" "Puppeteer error: $RERUN_OUTPUT"
    continue
  }
  
  echo "✅ Rerun triggered successfully"
  
  # Wait a bit for checks to start
  echo "⏳ Waiting 5 seconds for checks to start..."
  sleep 5
  
  # Get updated status
  UPDATED_INFO=$(gh pr view "$pr_num" --json statusCheckRollup 2>/dev/null || echo "")
  CURRENT_CHECKS=$(echo "$UPDATED_INFO" | jq -r '.statusCheckRollup[]? | "\(.name): \(.conclusion // .status)"' | head -10)
  
  # Log results
  DETAILS="## Failing Checks Before Rerun
\`\`\`
$FAILING_CHECKS
\`\`\`

## Current Check Status (After Rerun)
\`\`\`
$CURRENT_CHECKS
\`\`\`

## Rerun Output
\`\`\`
$RERUN_OUTPUT
\`\`\`
"
  
  log_report "$pr_num" "RERUN_TRIGGERED" "$DETAILS"
  
  # macOS notification (if enabled)
  if [[ "${ENABLE_NOTIFICATIONS:-1}" == "1" ]]; then
    osascript -e "display notification \"Rerun triggered for PR #$pr_num\" with title \"CI Watcher\" subtitle \"$PR_TITLE\"" 2>/dev/null || true
  fi
  
  # --- Redis event bus (optional, non-blocking) ---
  if [[ -n "${LUKA_REDIS_URL:-}" ]] && command -v redis-cli >/dev/null 2>&1; then
    "${HOME}/02luka/tools/ci/redis_pub.zsh" ci:events "$(jq -n \
      --arg repo "Ic1558/02luka" \
      --argjson pr "$pr_num" \
      --arg type "pr.rerun.request" \
      --arg time "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
      '{type:$type, repo:$repo, pr:$pr, time:$time}')" 2>/dev/null || true
  fi
  
  echo "✅ PR #$pr_num processed"
done

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ CI Watcher complete"
echo "📁 Reports saved to: $REPORT_DIR"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

