#!/usr/bin/env bash
# Phase 21 PR Creation Helper
# Generates links and commands for creating all three Phase 21 PRs

set -euo pipefail

cat <<'BANNER'
╔═══════════════════════════════════════════════════════════════════╗
║            Phase 21: Hub Infrastructure — PR Creator              ║
╚═══════════════════════════════════════════════════════════════════╝
BANNER

SID="011CUvQ8F4cVZPzH4rT1a1cM"
REPO_BASE="https://github.com/Ic1558/02luka"

echo ""
echo "📋 Three PRs ready to create:"
echo ""

# Phase 21.1
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1️⃣  PHASE 21.1 — Hub Mini UI"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Branch:  claude/phase-21-1-hub-mini-ui-${SID}"
echo "Title:   feat(phase-21.1): Hub Mini UI (static status & API shim)"
echo "URL:     ${REPO_BASE}/pull/new/claude/phase-21-1-hub-mini-ui-${SID}"
echo ""
echo "PR Body: .pr-templates/phase-21-1-hub-mini-ui.md"
echo ""
echo "Files:"
echo "  • hub/ui/index.html          — Dashboard HTML"
echo "  • hub/ui/app.js              — JSON fetcher"
echo "  • hub/ui/style.css           — Minimal styles"
echo "  • tools/hub_http.zsh         — Dev server (port 8080)"
echo "  • .github/workflows/hub-ui-check.yml — CI validation"
echo ""
echo "Quick Test:"
echo "  ./tools/hub_http.zsh"
echo "  open http://localhost:8080/ui/index.html"
echo ""

# Phase 21.2
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "2️⃣  PHASE 21.2 — Memory Guard"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Branch:  claude/phase-21-2-memory-guard-${SID}"
echo "Title:   feat(phase-21.2): Memory repo size/pattern guard"
echo "URL:     ${REPO_BASE}/pull/new/claude/phase-21-2-memory-guard-${SID}"
echo ""
echo "PR Body: .pr-templates/phase-21-2-memory-guard.md"
echo ""
echo "Files:"
echo "  • config/memory_guard.yaml   — Thresholds & patterns"
echo "  • config/schemas/memory_guard.schema.json — Validation schema"
echo "  • tools/check_memory_guard.zsh — Local enforcer"
echo "  • .github/workflows/memory-guard.yml — CI workflow"
echo ""
echo "Quick Test:"
echo "  LUKA_MEM_REPO_ROOT=\"\$HOME/LocalProjects/02luka-memory\" ./tools/check_memory_guard.zsh"
echo ""

# Phase 21.3
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "3️⃣  PHASE 21.3 — Protection Enforcer"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Branch:  claude/phase-21-3-protection-enforcer-${SID}"
echo "Title:   feat(phase-21.3): Branch protection enforcer & PR comment"
echo "URL:     ${REPO_BASE}/pull/new/claude/phase-21-3-protection-enforcer-${SID}"
echo ""
echo "PR Body: .pr-templates/phase-21-3-protection-enforcer.md"
echo ""
echo "Files:"
echo "  • config/required_checks.json — Required job IDs"
echo "  • tools/required_checks_assert.mjs — Local validator"
echo "  • .github/workflows/protection-enforcer.yml — CI + auto-comment"
echo ""
echo "Quick Test:"
echo "  node tools/required_checks_assert.mjs"
echo ""

# Summary
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 SUMMARY"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Total files:     12 files across 3 PRs"
echo "Total LOC:       ~269 lines"
echo "All branches:    Pushed ✓"
echo "PR templates:    Ready in .pr-templates/"
echo ""
echo "🚀 TO CREATE PRs:"
echo ""
echo "Option 1 (Web UI — Recommended):"
echo "  1. Click each URL above"
echo "  2. Copy content from corresponding .pr-templates/*.md file"
echo "  3. Paste into PR body"
echo "  4. Click 'Create pull request'"
echo ""
echo "Option 2 (Command Line):"
echo "  # Requires gh CLI and appropriate permissions"
echo "  gh pr create --title \"feat(phase-21.1): Hub Mini UI (static status & API shim)\" \\"
echo "    --body-file .pr-templates/phase-21-1-hub-mini-ui.md \\"
echo "    --head claude/phase-21-1-hub-mini-ui-${SID}"
echo ""
echo "  gh pr create --title \"feat(phase-21.2): Memory repo size/pattern guard\" \\"
echo "    --body-file .pr-templates/phase-21-2-memory-guard.md \\"
echo "    --head claude/phase-21-2-memory-guard-${SID}"
echo ""
echo "  gh pr create --title \"feat(phase-21.3): Branch protection enforcer & PR comment\" \\"
echo "    --body-file .pr-templates/phase-21-3-protection-enforcer.md \\"
echo "    --head claude/phase-21-3-protection-enforcer-${SID}"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✨ All Phase 21 infrastructure components ready for review!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
