#!/usr/bin/env zsh
# protocol_v3_report_generator.zsh
# Generate Protocol v3.2 compliance reports
set -euo pipefail

SOT="${SOT:-$HOME/02luka}"
REPORT_DIR="${REPORT_DIR:-$SOT/g/reports/system}"
DATE=$(date +%Y%m%d_%H%M%S)
REPORT_FILE="$REPORT_DIR/protocol_v3_compliance_${DATE}.md"

echo "[report] Protocol v3.2 Compliance Report Generator"
echo "[report] Report: $REPORT_FILE"

{
  echo "# Protocol v3.2 Compliance Report"
  echo ""
  echo "**Date:** $(date -Iseconds)"
  echo "**Generated by:** protocol_v3_report_generator.zsh"
  echo ""
  echo "---"
  echo ""
  echo "## 1. Workflow Compliance"
  echo ""
  
  # Check bridge-selfcheck.yml
  if "$SOT/g/tools/verify_protocol_v3_compliance.zsh" "$SOT/.github/workflows/bridge-selfcheck.yml" 2>&1; then
    echo "✅ bridge-selfcheck.yml: Compliant"
  else
    echo "❌ bridge-selfcheck.yml: Non-compliant"
  fi
  
  echo ""
  echo "## 2. MLS Events"
  echo ""
  
  # Check recent MLS events
  if "$SOT/g/tools/mls_event_verifier.zsh" 2>&1; then
    echo "✅ MLS events verified"
  else
    echo "⚠️  MLS events check incomplete"
  fi
  
  echo ""
  echo "## 3. Recent Workflow Runs"
  echo ""
  echo "Checking last 5 workflow runs..."
  
  gh run list --workflow bridge-selfcheck.yml --limit 5 --json databaseId,conclusion,createdAt --jq '.[] | "  - Run \(.databaseId): \(.conclusion) (\(.createdAt))"' 2>&1 || echo "  ⚠️  Could not fetch workflow runs"
  
  echo ""
  echo "---"
  echo ""
  echo "**Report generated:** $(date -Iseconds)"
} > "$REPORT_FILE"

echo "[report] ✅ Report generated: $REPORT_FILE"
cat "$REPORT_FILE"
exit 0
