name: Auto Update PR branches

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: prs
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const { data } = await github.rest.pulls.list({ owner: context.repo.owner, repo: context.repo.repo, state: "open" });
            return data
              .filter(pr => pr.head.repo.full_name === context.repo.full_name)
              .map(pr => pr.head.ref)
              .join(" ");

      - if: ${{ steps.prs.outputs.result != '' }}
        run: |
          for BR in ${{ steps.prs.outputs.result }}; do
            echo "Updating $BR"
            git fetch origin $BR main --depth=1
            git checkout -B $BR origin/$BR
            (git merge --no-edit origin/main || git rebase origin/main)
            git push --force-with-lease origin $BR || true
          done


